/**
 * Indian OPD formulary — 162 curated molecules expanded by strength.
 *
 * WHERE THIS CAME FROM, AND WHAT IT IS NOT
 * India has no open, government-published brand-level drug registry. NLEM 2022 is
 * a molecule-only PDF, CDSCO publishes no queryable formulary, NPPA covers 540
 * price-controlled formulations, and RxNorm explicitly does not carry non-US
 * brands. There is a widely-reposted ~254k-row scrape of a commercial pharmacy
 * site on GitHub and Kaggle; we deliberately DID NOT ingest it. An uploader
 * tagging a scrape "MIT" does not launder a site's terms of service, and this is
 * a commercial product.
 *
 * So this list is hand-curated instead: every brand here is one confirmed to
 * exist in the Indian market, and uncertain combination brands were dropped
 * rather than guessed. It covers the medicines that make up the overwhelming
 * majority of real OPD volume, not the long tail.
 *
 * THE CATALOGUE IS NOT A SAFETY BOUNDARY.
 * Anything missing is still prescribable as free text — the doctor is the
 * prescriber and our incompleteness is our problem, not theirs. And the
 * controlled-substance block does NOT depend on this file: controlled.ts screens
 * the raw text, so an unseeded narcotic still blocks. This list exists to make
 * typing and dictation faster, nothing more.
 */

export interface SeedMedication {
  canonicalName: string;
  genericName: string | null;
  brandName: string | null;
  strength: string | null;
  strengthUnit: string | null;
  dosageForm: string | null;
  route: string | null;
  therapeuticClass: string | null;
  aliases: string[];
}

export const INDIA_OPD_FORMULARY: SeedMedication[] = [
  { canonicalName: 'Amoxicillin 250 mg', genericName: 'Amoxicillin', brandName: 'Mox', strength: '250', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Penicillin antibiotic',
    aliases: ['amoxicillin', 'amoxicillin 250', 'amoxil', 'amoxil 250', 'mox', 'mox 250', 'novamox', 'novamox 250'] },
  { canonicalName: 'Amoxicillin 500 mg', genericName: 'Amoxicillin', brandName: 'Mox', strength: '500', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Penicillin antibiotic',
    aliases: ['amoxicillin', 'amoxicillin 500', 'amoxil', 'amoxil 500', 'mox', 'mox 500', 'novamox', 'novamox 500'] },
  { canonicalName: 'Amoxicillin + Clavulanic acid 625 mg', genericName: 'Amoxicillin + Clavulanic acid', brandName: 'Augmentin', strength: '625', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta-lactam + beta-lactamase inhibitor',
    aliases: ['amoxicillin', 'amoxicillin + clavulanic acid', 'amoxicillin + clavulanic acid 625', 'augmentin', 'augmentin 625', 'clavam', 'clavam 625', 'clavulanic acid', 'moxikind-cv', 'moxikind-cv 625'] },
  { canonicalName: 'Amoxicillin + Clavulanic acid 375 mg', genericName: 'Amoxicillin + Clavulanic acid', brandName: 'Augmentin', strength: '375', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta-lactam + beta-lactamase inhibitor',
    aliases: ['amoxicillin', 'amoxicillin + clavulanic acid', 'amoxicillin + clavulanic acid 375', 'augmentin', 'augmentin 375', 'clavam', 'clavam 375', 'clavulanic acid', 'moxikind-cv', 'moxikind-cv 375'] },
  { canonicalName: 'Azithromycin 250 mg', genericName: 'Azithromycin', brandName: 'Azithral', strength: '250', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Macrolide',
    aliases: ['azee', 'azee 250', 'azithral', 'azithral 250', 'azithromycin', 'azithromycin 250', 'zithrox', 'zithrox 250'] },
  { canonicalName: 'Azithromycin 500 mg', genericName: 'Azithromycin', brandName: 'Azithral', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Macrolide',
    aliases: ['azee', 'azee 500', 'azithral', 'azithral 500', 'azithromycin', 'azithromycin 500', 'zithrox', 'zithrox 500'] },
  { canonicalName: 'Cefixime 200 mg', genericName: 'Cefixime', brandName: 'Taxim-O', strength: '200', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '3rd-gen cephalosporin',
    aliases: ['cefixime', 'cefixime 200', 'mahacef', 'mahacef 200', 'taxim-o', 'taxim-o 200', 'zifi', 'zifi 200'] },
  { canonicalName: 'Cefpodoxime proxetil 100 mg', genericName: 'Cefpodoxime proxetil', brandName: 'Cepodem', strength: '100', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '3rd-gen cephalosporin',
    aliases: ['cefakind', 'cefakind 100', 'cefpodoxime proxetil', 'cefpodoxime proxetil 100', 'cepodem', 'cepodem 100'] },
  { canonicalName: 'Cefpodoxime proxetil 200 mg', genericName: 'Cefpodoxime proxetil', brandName: 'Cepodem', strength: '200', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '3rd-gen cephalosporin',
    aliases: ['cefakind', 'cefakind 200', 'cefpodoxime proxetil', 'cefpodoxime proxetil 200', 'cepodem', 'cepodem 200'] },
  { canonicalName: 'Cefuroxime axetil 250 mg', genericName: 'Cefuroxime axetil', brandName: 'Zinnat', strength: '250', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '2nd-gen cephalosporin',
    aliases: ['cefuroxime axetil', 'cefuroxime axetil 250', 'supacef', 'supacef 250', 'zinnat', 'zinnat 250'] },
  { canonicalName: 'Cefuroxime axetil 500 mg', genericName: 'Cefuroxime axetil', brandName: 'Zinnat', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '2nd-gen cephalosporin',
    aliases: ['cefuroxime axetil', 'cefuroxime axetil 500', 'supacef', 'supacef 500', 'zinnat', 'zinnat 500'] },
  { canonicalName: 'Cephalexin 250 mg', genericName: 'Cephalexin', brandName: 'Sporidex', strength: '250', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: '1st-gen cephalosporin',
    aliases: ['cephalexin', 'cephalexin 250', 'sporidex', 'sporidex 250'] },
  { canonicalName: 'Cephalexin 500 mg', genericName: 'Cephalexin', brandName: 'Sporidex', strength: '500', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: '1st-gen cephalosporin',
    aliases: ['cephalexin', 'cephalexin 500', 'sporidex', 'sporidex 500'] },
  { canonicalName: 'Ceftriaxone 1 g', genericName: 'Ceftriaxone', brandName: 'Monocef', strength: '1', strengthUnit: 'g', dosageForm: 'injection', route: 'IV', therapeuticClass: '3rd-gen cephalosporin',
    aliases: ['ceftriaxone', 'ceftriaxone 1', 'intacef', 'intacef 1', 'monocef', 'monocef 1'] },
  { canonicalName: 'Cefotaxime 1 g', genericName: 'Cefotaxime', brandName: 'Taxim', strength: '1', strengthUnit: 'g', dosageForm: 'injection', route: 'IV', therapeuticClass: '3rd-gen cephalosporin',
    aliases: ['cefotaxime', 'cefotaxime 1', 'taxim', 'taxim 1'] },
  { canonicalName: 'Piperacillin + Tazobactam 4.5 g', genericName: 'Piperacillin + Tazobactam', brandName: 'Piptaz', strength: '4.5', strengthUnit: 'g', dosageForm: 'injection', route: 'IV', therapeuticClass: 'Extended-spectrum penicillin + BLI',
    aliases: ['piperacillin', 'piperacillin + tazobactam', 'piperacillin + tazobactam 4.5', 'piptaz', 'piptaz 4.5', 'tazobactam'] },
  { canonicalName: 'Ciprofloxacin 500 mg', genericName: 'Ciprofloxacin', brandName: 'Ciplox', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Fluoroquinolone',
    aliases: ['cifran', 'cifran 500', 'ciplox', 'ciplox 500', 'ciprofloxacin', 'ciprofloxacin 500'] },
  { canonicalName: 'Ofloxacin 200 mg', genericName: 'Ofloxacin', brandName: 'Zanocin', strength: '200', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Fluoroquinolone',
    aliases: ['oflox', 'oflox 200', 'ofloxacin', 'ofloxacin 200', 'zanocin', 'zanocin 200'] },
  { canonicalName: 'Ofloxacin + Ornidazole 200 mg', genericName: 'Ofloxacin + Ornidazole', brandName: 'O2', strength: '200', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Fluoroquinolone + antiprotozoal',
    aliases: ['o2', 'o2 200', 'oflomac-oz', 'oflomac-oz 200', 'ofloxacin', 'ofloxacin + ornidazole', 'ofloxacin + ornidazole 200', 'ornidazole'] },
  { canonicalName: 'Levofloxacin 500 mg', genericName: 'Levofloxacin', brandName: 'Levoflox', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Fluoroquinolone',
    aliases: ['glevo', 'glevo 500', 'levoflox', 'levoflox 500', 'levofloxacin', 'levofloxacin 500'] },
  { canonicalName: 'Norfloxacin + Tinidazole 400 mg', genericName: 'Norfloxacin + Tinidazole', brandName: 'Norflox-TZ', strength: '400', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Fluoroquinolone + antiprotozoal',
    aliases: ['norflox-tz', 'norflox-tz 400', 'norfloxacin', 'norfloxacin + tinidazole', 'norfloxacin + tinidazole 400', 'tinidazole'] },
  { canonicalName: 'Doxycycline 100 mg', genericName: 'Doxycycline', brandName: 'Doxy-1', strength: '100', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Tetracycline',
    aliases: ['doxt-sl', 'doxt-sl 100', 'doxy-1', 'doxy-1 100', 'doxycycline', 'doxycycline 100'] },
  { canonicalName: 'Metronidazole 400 mg', genericName: 'Metronidazole', brandName: 'Flagyl', strength: '400', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Nitroimidazole',
    aliases: ['flagyl', 'flagyl 400', 'metrogyl', 'metrogyl 400', 'metronidazole', 'metronidazole 400'] },
  { canonicalName: 'Clindamycin 300 mg', genericName: 'Clindamycin', brandName: 'Dalacin-C', strength: '300', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Lincosamide',
    aliases: ['clindac-a (topical)', 'clindac-a (topical) 300', 'clindamycin', 'clindamycin 300', 'dalacin-c', 'dalacin-c 300'] },
  { canonicalName: 'Clindamycin 1 %', genericName: 'Clindamycin', brandName: 'Dalacin-C', strength: '1', strengthUnit: '%', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Lincosamide',
    aliases: ['clindac-a (topical)', 'clindac-a (topical) 1', 'clindamycin', 'clindamycin 1', 'dalacin-c', 'dalacin-c 1'] },
  { canonicalName: 'Roxithromycin 150 mg', genericName: 'Roxithromycin', brandName: 'Roxid', strength: '150', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Macrolide',
    aliases: ['roxid', 'roxid 150', 'roxithromycin', 'roxithromycin 150'] },
  { canonicalName: 'Linezolid 600 mg', genericName: 'Linezolid', brandName: 'Linospan', strength: '600', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Oxazolidinone (reserve antibiotic)',
    aliases: ['linezolid', 'linezolid 600', 'linospan', 'linospan 600'] },
  { canonicalName: 'Nitrofurantoin 100 mg', genericName: 'Nitrofurantoin', brandName: 'Niftran', strength: '100', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Urinary antiseptic',
    aliases: ['niftran', 'niftran 100', 'nitrofurantoin', 'nitrofurantoin 100'] },
  { canonicalName: 'Amikacin 500 mg', genericName: 'Amikacin', brandName: 'Mikacin', strength: '500', strengthUnit: 'mg', dosageForm: 'injection', route: 'IV', therapeuticClass: 'Aminoglycoside',
    aliases: ['amikacin', 'amikacin 500', 'mikacin', 'mikacin 500'] },
  { canonicalName: 'Albendazole 400 mg', genericName: 'Albendazole', brandName: 'Zentel', strength: '400', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Anthelmintic',
    aliases: ['albendazole', 'albendazole 400', 'bandy', 'bandy 400', 'wormin', 'wormin 400', 'zentel', 'zentel 400'] },
  { canonicalName: 'Ivermectin 6 mg', genericName: 'Ivermectin', brandName: 'Ivecop', strength: '6', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiparasitic',
    aliases: ['ivecop', 'ivecop 6', 'ivermectin', 'ivermectin 6', 'scabo', 'scabo 6'] },
  { canonicalName: 'Ivermectin 12 mg', genericName: 'Ivermectin', brandName: 'Ivecop', strength: '12', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiparasitic',
    aliases: ['ivecop', 'ivecop 12', 'ivermectin', 'ivermectin 12', 'scabo', 'scabo 12'] },
  { canonicalName: 'Paracetamol 500 mg', genericName: 'Paracetamol', brandName: 'Dolo', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Analgesic-antipyretic',
    aliases: ['calpol', 'calpol 500', 'crocin', 'crocin 500', 'dolo', 'dolo 500', 'paracetamol', 'paracetamol 500'] },
  { canonicalName: 'Paracetamol 650 mg', genericName: 'Paracetamol', brandName: 'Dolo', strength: '650', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Analgesic-antipyretic',
    aliases: ['calpol', 'calpol 650', 'crocin', 'crocin 650', 'dolo', 'dolo 650', 'paracetamol', 'paracetamol 650'] },
  { canonicalName: 'Paracetamol + Ibuprofen 325 mg', genericName: 'Paracetamol + Ibuprofen', brandName: 'Combiflam', strength: '325', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID combo',
    aliases: ['combiflam', 'combiflam 325', 'ibugesic plus', 'ibugesic plus 325', 'ibuprofen', 'paracetamol', 'paracetamol + ibuprofen', 'paracetamol + ibuprofen 325'] },
  { canonicalName: 'Ibuprofen 400 mg', genericName: 'Ibuprofen', brandName: 'Brufen', strength: '400', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID',
    aliases: ['brufen', 'brufen 400', 'ibuprofen', 'ibuprofen 400'] },
  { canonicalName: 'Diclofenac 50 mg', genericName: 'Diclofenac', brandName: 'Voveran', strength: '50', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID',
    aliases: ['diclofenac', 'diclofenac 50', 'voltaflam', 'voltaflam 50', 'voveran', 'voveran 50'] },
  { canonicalName: 'Aceclofenac 100 mg', genericName: 'Aceclofenac', brandName: 'Zerodol', strength: '100', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID',
    aliases: ['aceclofenac', 'aceclofenac 100', 'hifenac', 'hifenac 100', 'zerodol', 'zerodol 100'] },
  { canonicalName: 'Aceclofenac + Paracetamol 100 mg', genericName: 'Aceclofenac + Paracetamol', brandName: 'Zerodol-P', strength: '100', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID combo',
    aliases: ['aceclofenac', 'aceclofenac + paracetamol', 'aceclofenac + paracetamol 100', 'hifenac-p', 'hifenac-p 100', 'paracetamol', 'zerodol-p', 'zerodol-p 100'] },
  { canonicalName: 'Aceclofenac + Serratiopeptidase 100 mg', genericName: 'Aceclofenac + Serratiopeptidase', brandName: 'Zerodol-SP', strength: '100', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID + proteolytic enzyme',
    aliases: ['aceclofenac', 'aceclofenac + serratiopeptidase', 'aceclofenac + serratiopeptidase 100', 'serratiopeptidase', 'zerodol-sp', 'zerodol-sp 100'] },
  { canonicalName: 'Etoricoxib 60 mg', genericName: 'Etoricoxib', brandName: 'Etoshine', strength: '60', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'COX-2 selective NSAID',
    aliases: ['etoricoxib', 'etoricoxib 60', 'etoshine', 'etoshine 60', 'nucoxia', 'nucoxia 60'] },
  { canonicalName: 'Etoricoxib 90 mg', genericName: 'Etoricoxib', brandName: 'Etoshine', strength: '90', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'COX-2 selective NSAID',
    aliases: ['etoricoxib', 'etoricoxib 90', 'etoshine', 'etoshine 90', 'nucoxia', 'nucoxia 90'] },
  { canonicalName: 'Nimesulide 100 mg', genericName: 'Nimesulide', brandName: 'Nimulid', strength: '100', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID',
    aliases: ['nimesulide', 'nimesulide 100', 'nimulid', 'nimulid 100', 'nise', 'nise 100'] },
  { canonicalName: 'Mefenamic acid + Dicyclomine 250 mg', genericName: 'Mefenamic acid + Dicyclomine', brandName: 'Meftal-Spas', strength: '250', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID + antispasmodic',
    aliases: ['dicyclomine', 'mefenamic acid', 'mefenamic acid + dicyclomine', 'mefenamic acid + dicyclomine 250', 'meftal-spas', 'meftal-spas 250'] },
  { canonicalName: 'Tramadol 50 mg', genericName: 'Tramadol', brandName: 'Tramazac', strength: '50', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Opioid analgesic',
    aliases: ['tramadol', 'tramadol 50', 'tramazac', 'tramazac 50'] },
  { canonicalName: 'Tramadol + Paracetamol 37.5 mg', genericName: 'Tramadol + Paracetamol', brandName: 'Ultracet', strength: '37.5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Opioid combo',
    aliases: ['paracetamol', 'tramadol', 'tramadol + paracetamol', 'tramadol + paracetamol 37.5', 'ultracet', 'ultracet 37.5'] },
  { canonicalName: 'Aspirin (antiplatelet dose) 75 mg', genericName: 'Aspirin (antiplatelet dose)', brandName: 'Ecosprin', strength: '75', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiplatelet',
    aliases: ['aspirin (antiplatelet dose)', 'aspirin (antiplatelet dose) 75', 'delisprin', 'delisprin 75', 'ecosprin', 'ecosprin 75'] },
  { canonicalName: 'Aspirin (antiplatelet dose) 150 mg', genericName: 'Aspirin (antiplatelet dose)', brandName: 'Ecosprin', strength: '150', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiplatelet',
    aliases: ['aspirin (antiplatelet dose)', 'aspirin (antiplatelet dose) 150', 'delisprin', 'delisprin 150', 'ecosprin', 'ecosprin 150'] },
  { canonicalName: 'Aspirin (analgesic dose) 350 mg', genericName: 'Aspirin (analgesic dose)', brandName: 'Disprin', strength: '350', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'NSAID/analgesic',
    aliases: ['aspirin (analgesic dose)', 'aspirin (analgesic dose) 350', 'disprin', 'disprin 350'] },
  { canonicalName: 'Trypsin-Chymotrypsin / Serratiopeptidase 100', genericName: 'Trypsin-Chymotrypsin / Serratiopeptidase', brandName: 'Chymoral Forte', strength: '100', strengthUnit: null, dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Proteolytic enzyme, anti-inflammatory',
    aliases: ['chymoral forte', 'chymoral forte 100', 'danzen', 'danzen 100', 'trypsin-chymotrypsin / serratiopeptidase', 'trypsin-chymotrypsin / serratiopeptidase 100'] },
  { canonicalName: 'Trypsin-Chymotrypsin / Serratiopeptidase 10 mg', genericName: 'Trypsin-Chymotrypsin / Serratiopeptidase', brandName: 'Chymoral Forte', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Proteolytic enzyme, anti-inflammatory',
    aliases: ['chymoral forte', 'chymoral forte 10', 'danzen', 'danzen 10', 'trypsin-chymotrypsin / serratiopeptidase', 'trypsin-chymotrypsin / serratiopeptidase 10'] },
  { canonicalName: 'Diclofenac (topical) 1', genericName: 'Diclofenac (topical)', brandName: 'Voveran Gel', strength: '1', strengthUnit: null, dosageForm: 'gel', route: 'topical', therapeuticClass: 'Topical NSAID',
    aliases: ['diclofenac (topical)', 'diclofenac (topical) 1', 'volini', 'volini 1', 'voveran gel', 'voveran gel 1'] },
  { canonicalName: 'Pantoprazole 40 mg', genericName: 'Pantoprazole', brandName: 'Pan', strength: '40', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Proton pump inhibitor',
    aliases: ['pan', 'pan 40', 'pantocid', 'pantocid 40', 'pantop', 'pantop 40', 'pantoprazole', 'pantoprazole 40'] },
  { canonicalName: 'Pantoprazole + Domperidone 40 mg', genericName: 'Pantoprazole + Domperidone', brandName: 'Pan-D', strength: '40', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'PPI + prokinetic',
    aliases: ['domperidone', 'pan-d', 'pan-d 40', 'pantocid-dsr', 'pantocid-dsr 40', 'pantoprazole', 'pantoprazole + domperidone', 'pantoprazole + domperidone 40'] },
  { canonicalName: 'Omeprazole 20 mg', genericName: 'Omeprazole', brandName: 'Omez', strength: '20', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Proton pump inhibitor',
    aliases: ['ocid', 'ocid 20', 'omeprazole', 'omeprazole 20', 'omez', 'omez 20'] },
  { canonicalName: 'Rabeprazole 20 mg', genericName: 'Rabeprazole', brandName: 'Rablet', strength: '20', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Proton pump inhibitor',
    aliases: ['rabeprazole', 'rabeprazole 20', 'rablet', 'rablet 20', 'razo', 'razo 20'] },
  { canonicalName: 'Rabeprazole + Domperidone 20 mg', genericName: 'Rabeprazole + Domperidone', brandName: 'Razo-D', strength: '20', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'PPI + prokinetic',
    aliases: ['domperidone', 'rabeprazole', 'rabeprazole + domperidone', 'rabeprazole + domperidone 20', 'rablet-d', 'rablet-d 20', 'razo-d', 'razo-d 20'] },
  { canonicalName: 'Esomeprazole 40 mg', genericName: 'Esomeprazole', brandName: 'Nexpro', strength: '40', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Proton pump inhibitor',
    aliases: ['esomeprazole', 'esomeprazole 40', 'esoz', 'esoz 40', 'nexpro', 'nexpro 40'] },
  { canonicalName: 'Famotidine 40 mg', genericName: 'Famotidine', brandName: 'Famocid', strength: '40', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'H2-receptor blocker',
    aliases: ['famocid', 'famocid 40', 'famotidine', 'famotidine 40'] },
  { canonicalName: 'Domperidone 10 mg', genericName: 'Domperidone', brandName: 'Domstal', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Prokinetic / antiemetic',
    aliases: ['domperidone', 'domperidone 10', 'domstal', 'domstal 10', 'vomistop', 'vomistop 10'] },
  { canonicalName: 'Drotaverine 80 mg', genericName: 'Drotaverine', brandName: 'Drotin', strength: '80', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antispasmodic',
    aliases: ['drotaverine', 'drotaverine 80', 'drotin', 'drotin 80'] },
  { canonicalName: 'Dicyclomine + Paracetamol 20 mg', genericName: 'Dicyclomine + Paracetamol', brandName: 'Cyclopam', strength: '20', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antispasmodic combo',
    aliases: ['cyclopam', 'cyclopam 20', 'dicyclomine', 'dicyclomine + paracetamol', 'dicyclomine + paracetamol 20', 'paracetamol'] },
  { canonicalName: 'Sucralfate 1 g', genericName: 'Sucralfate', brandName: 'Sucral', strength: '1', strengthUnit: 'g', dosageForm: 'suspension', route: 'oral', therapeuticClass: 'Mucosal protectant',
    aliases: ['sucral', 'sucral 1', 'sucralfate', 'sucralfate 1'] },
  { canonicalName: 'Sucralfate 10 ml', genericName: 'Sucralfate', brandName: 'Sucral', strength: '10', strengthUnit: 'ml', dosageForm: 'suspension', route: 'oral', therapeuticClass: 'Mucosal protectant',
    aliases: ['sucral', 'sucral 10', 'sucralfate', 'sucralfate 10'] },
  { canonicalName: 'Oral rehydration salts', genericName: 'Oral rehydration salts', brandName: 'Electral', strength: null, strengthUnit: null, dosageForm: 'sachet', route: 'oral', therapeuticClass: 'Rehydration therapy',
    aliases: ['electral', 'oral rehydration salts', 'orsl'] },
  { canonicalName: 'Loperamide 2 mg', genericName: 'Loperamide', brandName: 'Eldoper', strength: '2', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Antidiarrheal',
    aliases: ['eldoper', 'eldoper 2', 'lopamide', 'lopamide 2', 'loperamide', 'loperamide 2'] },
  { canonicalName: 'Racecadotril 100 mg', genericName: 'Racecadotril', brandName: 'Redotil', strength: '100', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Antidiarrheal (antisecretory)',
    aliases: ['racecadotril', 'racecadotril 100', 'redotil', 'redotil 100'] },
  { canonicalName: 'Racecadotril 10 mg', genericName: 'Racecadotril', brandName: 'Redotil', strength: '10', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Antidiarrheal (antisecretory)',
    aliases: ['racecadotril', 'racecadotril 10', 'redotil', 'redotil 10'] },
  { canonicalName: 'Lactulose 10 g', genericName: 'Lactulose', brandName: 'Duphalac', strength: '10', strengthUnit: 'g', dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Osmotic laxative',
    aliases: ['duphalac', 'duphalac 10', 'lactulose', 'lactulose 10', 'looz', 'looz 10'] },
  { canonicalName: 'Lactulose 15 ml', genericName: 'Lactulose', brandName: 'Duphalac', strength: '15', strengthUnit: 'ml', dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Osmotic laxative',
    aliases: ['duphalac', 'duphalac 15', 'lactulose', 'lactulose 15', 'looz', 'looz 15'] },
  { canonicalName: 'Ispaghula husk', genericName: 'Ispaghula husk', brandName: 'Sat-Isabgol', strength: null, strengthUnit: null, dosageForm: 'powder', route: 'oral', therapeuticClass: 'Bulk-forming laxative',
    aliases: ['fibrolife', 'ispaghula husk', 'sat-isabgol'] },
  { canonicalName: 'Bisacodyl 5 mg', genericName: 'Bisacodyl', brandName: 'Dulcolax', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Stimulant laxative',
    aliases: ['bisacodyl', 'bisacodyl 5', 'dulcolax', 'dulcolax 5'] },
  { canonicalName: 'Aluminium/Magnesium hydroxide + Simethicone', genericName: 'Aluminium/Magnesium hydroxide + Simethicone', brandName: 'Digene', strength: null, strengthUnit: null, dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antacid',
    aliases: ['aluminium/magnesium hydroxide', 'aluminium/magnesium hydroxide + simethicone', 'digene', 'gelusil', 'simethicone'] },
  { canonicalName: 'Ursodeoxycholic acid 150 mg', genericName: 'Ursodeoxycholic acid', brandName: 'Udiliv', strength: '150', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Hepatoprotective (choleretic)',
    aliases: ['udiliv', 'udiliv 150', 'ursodeoxycholic acid', 'ursodeoxycholic acid 150'] },
  { canonicalName: 'Ursodeoxycholic acid 300 mg', genericName: 'Ursodeoxycholic acid', brandName: 'Udiliv', strength: '300', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Hepatoprotective (choleretic)',
    aliases: ['udiliv', 'udiliv 300', 'ursodeoxycholic acid', 'ursodeoxycholic acid 300'] },
  { canonicalName: 'Amlodipine 5 mg', genericName: 'Amlodipine', brandName: 'Amlodac', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Calcium channel blocker',
    aliases: ['amlodac', 'amlodac 5', 'amlodipine', 'amlodipine 5', 'amlokind', 'amlokind 5', 'amlopres', 'amlopres 5'] },
  { canonicalName: 'Amlodipine 10 mg', genericName: 'Amlodipine', brandName: 'Amlodac', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Calcium channel blocker',
    aliases: ['amlodac', 'amlodac 10', 'amlodipine', 'amlodipine 10', 'amlokind', 'amlokind 10', 'amlopres', 'amlopres 10'] },
  { canonicalName: 'Telmisartan 20 mg', genericName: 'Telmisartan', brandName: 'Telma', strength: '20', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Angiotensin receptor blocker',
    aliases: ['telma', 'telma 20', 'telmisartan', 'telmisartan 20', 'telsar', 'telsar 20'] },
  { canonicalName: 'Telmisartan 40 mg', genericName: 'Telmisartan', brandName: 'Telma', strength: '40', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Angiotensin receptor blocker',
    aliases: ['telma', 'telma 40', 'telmisartan', 'telmisartan 40', 'telsar', 'telsar 40'] },
  { canonicalName: 'Telmisartan 80 mg', genericName: 'Telmisartan', brandName: 'Telma', strength: '80', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Angiotensin receptor blocker',
    aliases: ['telma', 'telma 80', 'telmisartan', 'telmisartan 80', 'telsar', 'telsar 80'] },
  { canonicalName: 'Telmisartan + Amlodipine 40 mg', genericName: 'Telmisartan + Amlodipine', brandName: 'Telma-AM', strength: '40', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'ARB + CCB combo',
    aliases: ['amlodipine', 'telma-am', 'telma-am 40', 'telmikind-am', 'telmikind-am 40', 'telmisartan', 'telmisartan + amlodipine', 'telmisartan + amlodipine 40'] },
  { canonicalName: 'Losartan 25 mg', genericName: 'Losartan', brandName: 'Losar', strength: '25', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Angiotensin receptor blocker',
    aliases: ['losar', 'losar 25', 'losartan', 'losartan 25', 'repace', 'repace 25'] },
  { canonicalName: 'Losartan 50 mg', genericName: 'Losartan', brandName: 'Losar', strength: '50', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Angiotensin receptor blocker',
    aliases: ['losar', 'losar 50', 'losartan', 'losartan 50', 'repace', 'repace 50'] },
  { canonicalName: 'Losartan + Hydrochlorothiazide 50 mg', genericName: 'Losartan + Hydrochlorothiazide', brandName: 'Losar-H', strength: '50', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'ARB + diuretic combo',
    aliases: ['hydrochlorothiazide', 'losar-h', 'losar-h 50', 'losartan', 'losartan + hydrochlorothiazide', 'losartan + hydrochlorothiazide 50', 'repace-h', 'repace-h 50'] },
  { canonicalName: 'Metoprolol succinate 25 mg', genericName: 'Metoprolol succinate', brandName: 'Metolar-XR', strength: '25', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta blocker',
    aliases: ['betaloc', 'betaloc 25', 'metolar-xr', 'metolar-xr 25', 'metoprolol succinate', 'metoprolol succinate 25'] },
  { canonicalName: 'Metoprolol succinate 50 mg', genericName: 'Metoprolol succinate', brandName: 'Metolar-XR', strength: '50', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta blocker',
    aliases: ['betaloc', 'betaloc 50', 'metolar-xr', 'metolar-xr 50', 'metoprolol succinate', 'metoprolol succinate 50'] },
  { canonicalName: 'Atenolol 25 mg', genericName: 'Atenolol', brandName: 'Aten', strength: '25', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta blocker',
    aliases: ['aten', 'aten 25', 'atenolol', 'atenolol 25', 'betacard', 'betacard 25'] },
  { canonicalName: 'Atenolol 50 mg', genericName: 'Atenolol', brandName: 'Aten', strength: '50', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta blocker',
    aliases: ['aten', 'aten 50', 'atenolol', 'atenolol 50', 'betacard', 'betacard 50'] },
  { canonicalName: 'Nebivolol 5 mg', genericName: 'Nebivolol', brandName: 'Nebicard', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta blocker (cardioselective)',
    aliases: ['nebicard', 'nebicard 5', 'nebivolol', 'nebivolol 5', 'nubeta', 'nubeta 5'] },
  { canonicalName: 'Enalapril 5 mg', genericName: 'Enalapril', brandName: 'Envas', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'ACE inhibitor',
    aliases: ['enalapril', 'enalapril 5', 'envas', 'envas 5'] },
  { canonicalName: 'Enalapril 10 mg', genericName: 'Enalapril', brandName: 'Envas', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'ACE inhibitor',
    aliases: ['enalapril', 'enalapril 10', 'envas', 'envas 10'] },
  { canonicalName: 'Ramipril 2.5 mg', genericName: 'Ramipril', brandName: 'Cardace', strength: '2.5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'ACE inhibitor',
    aliases: ['cardace', 'cardace 2.5', 'ramipril', 'ramipril 2.5'] },
  { canonicalName: 'Ramipril 5 mg', genericName: 'Ramipril', brandName: 'Cardace', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'ACE inhibitor',
    aliases: ['cardace', 'cardace 5', 'ramipril', 'ramipril 5'] },
  { canonicalName: 'Cilnidipine 10 mg', genericName: 'Cilnidipine', brandName: 'Cilacar', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Calcium channel blocker',
    aliases: ['cilacar', 'cilacar 10', 'cilnidipine', 'cilnidipine 10'] },
  { canonicalName: 'Clonidine 0.1 mg', genericName: 'Clonidine', brandName: 'Arkamin', strength: '0.1', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Central alpha-2 agonist',
    aliases: ['arkamin', 'arkamin 0.1', 'clonidine', 'clonidine 0.1'] },
  { canonicalName: 'Metformin 500 mg', genericName: 'Metformin', brandName: 'Glycomet', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Biguanide',
    aliases: ['glyciphage', 'glyciphage 500', 'glycomet', 'glycomet 500', 'metformin', 'metformin 500'] },
  { canonicalName: 'Metformin 850 mg', genericName: 'Metformin', brandName: 'Glycomet', strength: '850', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Biguanide',
    aliases: ['glyciphage', 'glyciphage 850', 'glycomet', 'glycomet 850', 'metformin', 'metformin 850'] },
  { canonicalName: 'Metformin 1000 mg', genericName: 'Metformin', brandName: 'Glycomet', strength: '1000', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Biguanide',
    aliases: ['glyciphage', 'glyciphage 1000', 'glycomet', 'glycomet 1000', 'metformin', 'metformin 1000'] },
  { canonicalName: 'Glimepiride 1 mg', genericName: 'Glimepiride', brandName: 'Amaryl', strength: '1', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Sulfonylurea',
    aliases: ['amaryl', 'amaryl 1', 'glimepiride', 'glimepiride 1', 'glimestar', 'glimestar 1'] },
  { canonicalName: 'Glimepiride 2 mg', genericName: 'Glimepiride', brandName: 'Amaryl', strength: '2', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Sulfonylurea',
    aliases: ['amaryl', 'amaryl 2', 'glimepiride', 'glimepiride 2', 'glimestar', 'glimestar 2'] },
  { canonicalName: 'Glimepiride + Metformin 1 mg', genericName: 'Glimepiride + Metformin', brandName: 'Glycomet-GP', strength: '1', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Combo',
    aliases: ['amaryl-m', 'amaryl-m 1', 'glimepiride', 'glimepiride + metformin', 'glimepiride + metformin 1', 'glycomet-gp', 'glycomet-gp 1', 'metformin'] },
  { canonicalName: 'Glimepiride + Metformin 2 mg', genericName: 'Glimepiride + Metformin', brandName: 'Glycomet-GP', strength: '2', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Combo',
    aliases: ['amaryl-m', 'amaryl-m 2', 'glimepiride', 'glimepiride + metformin', 'glimepiride + metformin 2', 'glycomet-gp', 'glycomet-gp 2', 'metformin'] },
  { canonicalName: 'Teneligliptin 20 mg', genericName: 'Teneligliptin', brandName: 'Zita', strength: '20', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'DPP-4 inhibitor',
    aliases: ['teneligliptin', 'teneligliptin 20', 'teneza', 'teneza 20', 'zita', 'zita 20'] },
  { canonicalName: 'Sitagliptin 100 mg', genericName: 'Sitagliptin', brandName: 'Januvia', strength: '100', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'DPP-4 inhibitor',
    aliases: ['istavel', 'istavel 100', 'januvia', 'januvia 100', 'sitagliptin', 'sitagliptin 100'] },
  { canonicalName: 'Sitagliptin + Metformin 50 mg', genericName: 'Sitagliptin + Metformin', brandName: 'Janumet', strength: '50', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Combo',
    aliases: ['istamet', 'istamet 50', 'janumet', 'janumet 50', 'metformin', 'sitagliptin', 'sitagliptin + metformin', 'sitagliptin + metformin 50'] },
  { canonicalName: 'Vildagliptin 50 mg', genericName: 'Vildagliptin', brandName: 'Galvus', strength: '50', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'DPP-4 inhibitor',
    aliases: ['galvus', 'galvus 50', 'jalra', 'jalra 50', 'vildagliptin', 'vildagliptin 50'] },
  { canonicalName: 'Voglibose 0.2 mg', genericName: 'Voglibose', brandName: 'Volix', strength: '0.2', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Alpha-glucosidase inhibitor',
    aliases: ['vobose', 'vobose 0.2', 'voglibose', 'voglibose 0.2', 'volix', 'volix 0.2'] },
  { canonicalName: 'Voglibose 0.3 mg', genericName: 'Voglibose', brandName: 'Volix', strength: '0.3', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Alpha-glucosidase inhibitor',
    aliases: ['vobose', 'vobose 0.3', 'voglibose', 'voglibose 0.3', 'volix', 'volix 0.3'] },
  { canonicalName: 'Dapagliflozin 10 mg', genericName: 'Dapagliflozin', brandName: 'Forxiga', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'SGLT2 inhibitor',
    aliases: ['dapagliflozin', 'dapagliflozin 10', 'forxiga', 'forxiga 10', 'oxra', 'oxra 10'] },
  { canonicalName: 'Empagliflozin 10 mg', genericName: 'Empagliflozin', brandName: 'Jardiance', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'SGLT2 inhibitor',
    aliases: ['empagliflozin', 'empagliflozin 10', 'jardiance', 'jardiance 10'] },
  { canonicalName: 'Empagliflozin 25 mg', genericName: 'Empagliflozin', brandName: 'Jardiance', strength: '25', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'SGLT2 inhibitor',
    aliases: ['empagliflozin', 'empagliflozin 25', 'jardiance', 'jardiance 25'] },
  { canonicalName: 'Pioglitazone 15 mg', genericName: 'Pioglitazone', brandName: 'Pioz', strength: '15', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Thiazolidinedione',
    aliases: ['pioglitazone', 'pioglitazone 15', 'pioz', 'pioz 15'] },
  { canonicalName: 'Pioglitazone 30 mg', genericName: 'Pioglitazone', brandName: 'Pioz', strength: '30', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Thiazolidinedione',
    aliases: ['pioglitazone', 'pioglitazone 30', 'pioz', 'pioz 30'] },
  { canonicalName: 'Insulin glargine 100 IU', genericName: 'Insulin glargine', brandName: 'Lantus', strength: '100', strengthUnit: 'IU', dosageForm: 'injection', route: 'IV', therapeuticClass: 'Long-acting insulin analogue',
    aliases: ['basalog', 'basalog 100', 'insulin glargine', 'insulin glargine 100', 'lantus', 'lantus 100'] },
  { canonicalName: 'Atorvastatin 10 mg', genericName: 'Atorvastatin', brandName: 'Atorva', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Statin',
    aliases: ['atorva', 'atorva 10', 'atorvastatin', 'atorvastatin 10', 'storvas', 'storvas 10'] },
  { canonicalName: 'Atorvastatin 20 mg', genericName: 'Atorvastatin', brandName: 'Atorva', strength: '20', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Statin',
    aliases: ['atorva', 'atorva 20', 'atorvastatin', 'atorvastatin 20', 'storvas', 'storvas 20'] },
  { canonicalName: 'Atorvastatin 40 mg', genericName: 'Atorvastatin', brandName: 'Atorva', strength: '40', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Statin',
    aliases: ['atorva', 'atorva 40', 'atorvastatin', 'atorvastatin 40', 'storvas', 'storvas 40'] },
  { canonicalName: 'Rosuvastatin 5 mg', genericName: 'Rosuvastatin', brandName: 'Rosuvas', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Statin',
    aliases: ['rosuvas', 'rosuvas 5', 'rosuvastatin', 'rosuvastatin 5', 'rozat', 'rozat 5'] },
  { canonicalName: 'Rosuvastatin 10 mg', genericName: 'Rosuvastatin', brandName: 'Rosuvas', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Statin',
    aliases: ['rosuvas', 'rosuvas 10', 'rosuvastatin', 'rosuvastatin 10', 'rozat', 'rozat 10'] },
  { canonicalName: 'Rosuvastatin 20 mg', genericName: 'Rosuvastatin', brandName: 'Rosuvas', strength: '20', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Statin',
    aliases: ['rosuvas', 'rosuvas 20', 'rosuvastatin', 'rosuvastatin 20', 'rozat', 'rozat 20'] },
  { canonicalName: 'Fenofibrate 160 mg', genericName: 'Fenofibrate', brandName: 'Lipicard', strength: '160', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Fibrate',
    aliases: ['fenofibrate', 'fenofibrate 160', 'lipicard', 'lipicard 160'] },
  { canonicalName: 'Cetirizine 10 mg', genericName: 'Cetirizine', brandName: 'Cetzine', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '2nd-gen antihistamine',
    aliases: ['alerid', 'alerid 10', 'cetirizine', 'cetirizine 10', 'cetzine', 'cetzine 10'] },
  { canonicalName: 'Levocetirizine 5 mg', genericName: 'Levocetirizine', brandName: 'Levocet', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '2nd-gen antihistamine',
    aliases: ['levocet', 'levocet 5', 'levocetirizine', 'levocetirizine 5', 'xyzal', 'xyzal 5'] },
  { canonicalName: 'Fexofenadine 120 mg', genericName: 'Fexofenadine', brandName: 'Allegra', strength: '120', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '2nd-gen antihistamine',
    aliases: ['allegra', 'allegra 120', 'fexofenadine', 'fexofenadine 120'] },
  { canonicalName: 'Fexofenadine 180 mg', genericName: 'Fexofenadine', brandName: 'Allegra', strength: '180', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '2nd-gen antihistamine',
    aliases: ['allegra', 'allegra 180', 'fexofenadine', 'fexofenadine 180'] },
  { canonicalName: 'Pheniramine maleate 25 mg', genericName: 'Pheniramine maleate', brandName: 'Avil', strength: '25', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '1st-gen antihistamine',
    aliases: ['avil', 'avil 25', 'pheniramine maleate', 'pheniramine maleate 25'] },
  { canonicalName: 'Hydroxyzine 10 mg', genericName: 'Hydroxyzine', brandName: 'Atarax', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antihistamine / anxiolytic',
    aliases: ['atarax', 'atarax 10', 'hydroxyzine', 'hydroxyzine 10'] },
  { canonicalName: 'Hydroxyzine 25 mg', genericName: 'Hydroxyzine', brandName: 'Atarax', strength: '25', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antihistamine / anxiolytic',
    aliases: ['atarax', 'atarax 25', 'hydroxyzine', 'hydroxyzine 25'] },
  { canonicalName: 'Montelukast 10 mg', genericName: 'Montelukast', brandName: 'Montair', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Leukotriene receptor antagonist',
    aliases: ['montair', 'montair 10', 'montek', 'montek 10', 'montelukast', 'montelukast 10'] },
  { canonicalName: 'Montelukast + Levocetirizine 10 mg', genericName: 'Montelukast + Levocetirizine', brandName: 'Montair-LC', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Combo',
    aliases: ['levocetirizine', 'montair-lc', 'montair-lc 10', 'montek-lc', 'montek-lc 10', 'montelukast', 'montelukast + levocetirizine', 'montelukast + levocetirizine 10'] },
  { canonicalName: 'Salbutamol 100 mcg', genericName: 'Salbutamol', brandName: 'Asthalin', strength: '100', strengthUnit: 'mcg', dosageForm: 'inhaler', route: 'inhalation', therapeuticClass: 'SABA bronchodilator',
    aliases: ['asthalin', 'asthalin 100', 'salbutamol', 'salbutamol 100'] },
  { canonicalName: 'Salbutamol 5 ml', genericName: 'Salbutamol', brandName: 'Asthalin', strength: '5', strengthUnit: 'ml', dosageForm: 'inhaler', route: 'inhalation', therapeuticClass: 'SABA bronchodilator',
    aliases: ['asthalin', 'asthalin 5', 'salbutamol', 'salbutamol 5'] },
  { canonicalName: 'Levosalbutamol 50 mcg', genericName: 'Levosalbutamol', brandName: 'Levolin', strength: '50', strengthUnit: 'mcg', dosageForm: 'inhaler', route: 'inhalation', therapeuticClass: 'SABA bronchodilator',
    aliases: ['levolin', 'levolin 50', 'levosalbutamol', 'levosalbutamol 50'] },
  { canonicalName: 'Budesonide 100', genericName: 'Budesonide', brandName: 'Budecort', strength: '100', strengthUnit: null, dosageForm: 'inhaler', route: 'inhalation', therapeuticClass: 'Inhaled corticosteroid',
    aliases: ['budecort', 'budecort 100', 'budesonide', 'budesonide 100', 'pulmicort', 'pulmicort 100'] },
  { canonicalName: 'Budesonide 200', genericName: 'Budesonide', brandName: 'Budecort', strength: '200', strengthUnit: null, dosageForm: 'inhaler', route: 'inhalation', therapeuticClass: 'Inhaled corticosteroid',
    aliases: ['budecort', 'budecort 200', 'budesonide', 'budesonide 200', 'pulmicort', 'pulmicort 200'] },
  { canonicalName: 'Budesonide 400 mcg', genericName: 'Budesonide', brandName: 'Budecort', strength: '400', strengthUnit: 'mcg', dosageForm: 'inhaler', route: 'inhalation', therapeuticClass: 'Inhaled corticosteroid',
    aliases: ['budecort', 'budecort 400', 'budesonide', 'budesonide 400', 'pulmicort', 'pulmicort 400'] },
  { canonicalName: 'Budesonide + Formoterol 200 mcg', genericName: 'Budesonide + Formoterol', brandName: 'Foracort', strength: '200', strengthUnit: 'mcg', dosageForm: 'inhaler', route: 'inhalation', therapeuticClass: 'ICS + LABA combo',
    aliases: ['budamate', 'budamate 200', 'budesonide', 'budesonide + formoterol', 'budesonide + formoterol 200', 'foracort', 'foracort 200', 'formoterol'] },
  { canonicalName: 'Theophylline + Etophylline', genericName: 'Theophylline + Etophylline', brandName: 'Deriphyllin', strength: null, strengthUnit: null, dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Bronchodilator',
    aliases: ['deriphyllin', 'etophylline', 'theophylline', 'theophylline + etophylline'] },
  { canonicalName: 'Ambroxol 30 mg', genericName: 'Ambroxol', brandName: 'Ambrolite', strength: '30', strengthUnit: 'mg', dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Mucolytic',
    aliases: ['ambrolite', 'ambrolite 30', 'ambroxol', 'ambroxol 30', 'mucolite', 'mucolite 30'] },
  { canonicalName: 'Ambroxol 5 ml', genericName: 'Ambroxol', brandName: 'Ambrolite', strength: '5', strengthUnit: 'ml', dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Mucolytic',
    aliases: ['ambrolite', 'ambrolite 5', 'ambroxol', 'ambroxol 5', 'mucolite', 'mucolite 5'] },
  { canonicalName: 'Bromhexine/Guaifenesin cough combo', genericName: 'Bromhexine/Guaifenesin cough combo', brandName: 'Ascoril', strength: null, strengthUnit: null, dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Expectorant combo',
    aliases: ['ascoril', 'bromhexine/guaifenesin cough combo', 'grilinctus'] },
  { canonicalName: 'Phenylephrine + Chlorpheniramine + Paracetamol', genericName: 'Phenylephrine + Chlorpheniramine + Paracetamol', brandName: 'Sinarest', strength: null, strengthUnit: null, dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Cold/decongestant combo',
    aliases: ['chlorpheniramine', 'd-cold total', 'paracetamol', 'phenylephrine', 'phenylephrine + chlorpheniramine + paracetamol', 'sinarest'] },
  { canonicalName: 'Xylometazoline 0.05 %', genericName: 'Xylometazoline', brandName: 'Otrivin', strength: '0.05', strengthUnit: '%', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Nasal decongestant',
    aliases: ['nasivion', 'nasivion 0.05', 'otrivin', 'otrivin 0.05', 'xylometazoline', 'xylometazoline 0.05'] },
  { canonicalName: 'Xylometazoline 0.1 %', genericName: 'Xylometazoline', brandName: 'Otrivin', strength: '0.1', strengthUnit: '%', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Nasal decongestant',
    aliases: ['nasivion', 'nasivion 0.1', 'otrivin', 'otrivin 0.1', 'xylometazoline', 'xylometazoline 0.1'] },
  { canonicalName: 'Ondansetron 4 mg', genericName: 'Ondansetron', brandName: 'Emeset', strength: '4', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '5-HT3 antagonist',
    aliases: ['emeset', 'emeset 4', 'ondansetron', 'ondansetron 4', 'ondem', 'ondem 4', 'vomikind', 'vomikind 4'] },
  { canonicalName: 'Ondansetron 8 mg', genericName: 'Ondansetron', brandName: 'Emeset', strength: '8', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: '5-HT3 antagonist',
    aliases: ['emeset', 'emeset 8', 'ondansetron', 'ondansetron 8', 'ondem', 'ondem 8', 'vomikind', 'vomikind 8'] },
  { canonicalName: 'Metoclopramide 10 mg', genericName: 'Metoclopramide', brandName: 'Perinorm', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Prokinetic / antiemetic',
    aliases: ['metoclopramide', 'metoclopramide 10', 'perinorm', 'perinorm 10'] },
  { canonicalName: 'Prochlorperazine 5 mg', genericName: 'Prochlorperazine', brandName: 'Stemetil', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiemetic (vertigo)',
    aliases: ['prochlorperazine', 'prochlorperazine 5', 'stemetil', 'stemetil 5'] },
  { canonicalName: 'Doxylamine + Pyridoxine 10 mg', genericName: 'Doxylamine + Pyridoxine', brandName: 'Doxinate', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiemetic (pregnancy-associated nausea)',
    aliases: ['doxinate', 'doxinate 10', 'doxylamine', 'doxylamine + pyridoxine', 'doxylamine + pyridoxine 10', 'pyridoxine'] },
  { canonicalName: 'Betahistine 8 mg', genericName: 'Betahistine', brandName: 'Vertin', strength: '8', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Anti-vertigo',
    aliases: ['betahistine', 'betahistine 8', 'vertin', 'vertin 8'] },
  { canonicalName: 'Betahistine 16 mg', genericName: 'Betahistine', brandName: 'Vertin', strength: '16', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Anti-vertigo',
    aliases: ['betahistine', 'betahistine 16', 'vertin', 'vertin 16'] },
  { canonicalName: 'Betahistine 24 mg', genericName: 'Betahistine', brandName: 'Vertin', strength: '24', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Anti-vertigo',
    aliases: ['betahistine', 'betahistine 24', 'vertin', 'vertin 24'] },
  { canonicalName: 'Vitamin B-complex', genericName: 'Vitamin B-complex', brandName: 'Becosules', strength: null, strengthUnit: null, dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Multivitamin (B group)',
    aliases: ['becosules', 'neurobion forte', 'polybion', 'vitamin b-complex'] },
  { canonicalName: 'Cholecalciferol (Vitamin D3) 60', genericName: 'Cholecalciferol (Vitamin D3)', brandName: 'Calcirol', strength: '60', strengthUnit: null, dosageForm: 'sachet', route: 'oral', therapeuticClass: 'Vitamin D',
    aliases: ['calcirol', 'calcirol 60', 'cholecalciferol (vitamin d3)', 'cholecalciferol (vitamin d3) 60', 'd-rise', 'd-rise 60', 'uprise-d3', 'uprise-d3 60'] },
  { canonicalName: 'Calcium + Vitamin D3 500 mg', genericName: 'Calcium + Vitamin D3', brandName: 'Shelcal', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Calcium supplement',
    aliases: ['calcium', 'calcium + vitamin d3', 'calcium + vitamin d3 500', 'ossofit', 'ossofit 500', 'shelcal', 'shelcal 500', 'vitamin d3'] },
  { canonicalName: 'Methylcobalamin (Vitamin B12) 500 mcg', genericName: 'Methylcobalamin (Vitamin B12)', brandName: 'Methycobal', strength: '500', strengthUnit: 'mcg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Vitamin B12',
    aliases: ['mecobion', 'mecobion 500', 'methycobal', 'methycobal 500', 'methylcobalamin (vitamin b12)', 'methylcobalamin (vitamin b12) 500', 'nervup', 'nervup 500'] },
  { canonicalName: 'Methylcobalamin (Vitamin B12) 1500 mcg', genericName: 'Methylcobalamin (Vitamin B12)', brandName: 'Methycobal', strength: '1500', strengthUnit: 'mcg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Vitamin B12',
    aliases: ['mecobion', 'mecobion 1500', 'methycobal', 'methycobal 1500', 'methylcobalamin (vitamin b12)', 'methylcobalamin (vitamin b12) 1500', 'nervup', 'nervup 1500'] },
  { canonicalName: 'Folic acid 5 mg', genericName: 'Folic acid', brandName: 'Folvite', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Vitamin (folate)',
    aliases: ['folic acid', 'folic acid 5', 'folvite', 'folvite 5'] },
  { canonicalName: 'Iron + Folic acid 100 mg', genericName: 'Iron + Folic acid', brandName: 'Autrin', strength: '100', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Hematinic',
    aliases: ['autrin', 'autrin 100', 'fefol', 'fefol 100', 'ferium xt', 'ferium xt 100', 'folic acid', 'iron', 'iron + folic acid', 'iron + folic acid 100'] },
  { canonicalName: 'Multivitamin/multimineral', genericName: 'Multivitamin/multimineral', brandName: 'Revital H', strength: null, strengthUnit: null, dosageForm: 'capsule', route: 'oral', therapeuticClass: 'General tonic',
    aliases: ['multivitamin/multimineral', 'revital h', 'supradyn', 'zincovit'] },
  { canonicalName: 'Vitamin C (ascorbic acid) 500 mg', genericName: 'Vitamin C (ascorbic acid)', brandName: 'Limcee', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Vitamin C',
    aliases: ['celin', 'celin 500', 'limcee', 'limcee 500', 'vitamin c (ascorbic acid)', 'vitamin c (ascorbic acid) 500'] },
  { canonicalName: 'Vitamin E (tocopherol) 400 mg', genericName: 'Vitamin E (tocopherol)', brandName: 'Evion', strength: '400', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Vitamin E',
    aliases: ['evion', 'evion 400', 'vitamin e (tocopherol)', 'vitamin e (tocopherol) 400'] },
  { canonicalName: 'Pregabalin 75 mg', genericName: 'Pregabalin', brandName: 'Pregeb', strength: '75', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Neuropathic pain / anticonvulsant',
    aliases: ['pregabalin', 'pregabalin 75', 'pregeb', 'pregeb 75'] },
  { canonicalName: 'Gabapentin 300 mg', genericName: 'Gabapentin', brandName: 'Gabapin', strength: '300', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Neuropathic pain / anticonvulsant',
    aliases: ['gabapentin', 'gabapentin 300', 'gabapin', 'gabapin 300'] },
  { canonicalName: 'Clotrimazole 1 %', genericName: 'Clotrimazole', brandName: 'Candid', strength: '1', strengthUnit: '%', dosageForm: 'cream', route: 'topical', therapeuticClass: 'Topical antifungal',
    aliases: ['candid', 'candid 1', 'canesten', 'canesten 1', 'clotrimazole', 'clotrimazole 1'] },
  { canonicalName: 'Clotrimazole + Beclomethasone + Neomycin', genericName: 'Clotrimazole + Beclomethasone + Neomycin', brandName: 'Candid-B', strength: null, strengthUnit: null, dosageForm: 'cream', route: 'topical', therapeuticClass: 'Topical steroid-antifungal-antibiotic combo',
    aliases: ['beclomethasone', 'candid-b', 'clotrimazole', 'clotrimazole + beclomethasone + neomycin', 'neomycin'] },
  { canonicalName: 'Mupirocin 2 %', genericName: 'Mupirocin', brandName: 'T-Bact', strength: '2', strengthUnit: '%', dosageForm: 'ointment', route: 'topical', therapeuticClass: 'Topical antibiotic',
    aliases: ['mupirocin', 'mupirocin 2', 't-bact', 't-bact 2'] },
  { canonicalName: 'Fusidic acid 2 %', genericName: 'Fusidic acid', brandName: 'Fucidin', strength: '2', strengthUnit: '%', dosageForm: 'cream', route: 'topical', therapeuticClass: 'Topical antibiotic',
    aliases: ['fucidin', 'fucidin 2', 'fusidic acid', 'fusidic acid 2'] },
  { canonicalName: 'Betamethasone 0.1 %', genericName: 'Betamethasone', brandName: 'Betnovate', strength: '0.1', strengthUnit: '%', dosageForm: 'cream', route: 'topical', therapeuticClass: 'Topical corticosteroid',
    aliases: ['betamethasone', 'betamethasone 0.1', 'betnovate', 'betnovate 0.1'] },
  { canonicalName: 'Calamine', genericName: 'Calamine', brandName: 'Lacto Calamine', strength: null, strengthUnit: null, dosageForm: 'lotion', route: 'topical', therapeuticClass: 'Topical soothant/antipruritic',
    aliases: ['caladryl', 'calamine', 'lacto calamine'] },
  { canonicalName: 'Povidone-iodine 5 %', genericName: 'Povidone-iodine', brandName: 'Betadine', strength: '5', strengthUnit: '%', dosageForm: 'ointment', route: 'topical', therapeuticClass: 'Antiseptic',
    aliases: ['betadine', 'betadine 5', 'povidone-iodine', 'povidone-iodine 5'] },
  { canonicalName: 'Povidone-iodine 10 %', genericName: 'Povidone-iodine', brandName: 'Betadine', strength: '10', strengthUnit: '%', dosageForm: 'ointment', route: 'topical', therapeuticClass: 'Antiseptic',
    aliases: ['betadine', 'betadine 10', 'povidone-iodine', 'povidone-iodine 10'] },
  { canonicalName: 'Silver sulfadiazine 1 %', genericName: 'Silver sulfadiazine', brandName: 'Silverex', strength: '1', strengthUnit: '%', dosageForm: 'cream', route: 'topical', therapeuticClass: 'Burns/antibacterial',
    aliases: ['silver sulfadiazine', 'silver sulfadiazine 1', 'silverex', 'silverex 1'] },
  { canonicalName: 'Permethrin 5 %', genericName: 'Permethrin', brandName: 'Scabex', strength: '5', strengthUnit: '%', dosageForm: 'lotion', route: 'topical', therapeuticClass: 'Scabicide',
    aliases: ['permethrin', 'permethrin 5', 'permite', 'permite 5', 'scabex', 'scabex 5'] },
  { canonicalName: 'Fluconazole 150 mg', genericName: 'Fluconazole', brandName: 'Forcan', strength: '150', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Systemic antifungal',
    aliases: ['fluconazole', 'fluconazole 150', 'forcan', 'forcan 150', 'zocon', 'zocon 150'] },
  { canonicalName: 'Itraconazole 100 mg', genericName: 'Itraconazole', brandName: 'Candiforce', strength: '100', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Systemic antifungal',
    aliases: ['candiforce', 'candiforce 100', 'itraconazole', 'itraconazole 100', 'itrasys', 'itrasys 100'] },
  { canonicalName: 'Terbinafine 250 mg', genericName: 'Terbinafine', brandName: 'Terbinaforce', strength: '250', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antifungal',
    aliases: ['sebifin', 'sebifin 250', 'terbinafine', 'terbinafine 250', 'terbinaforce', 'terbinaforce 250'] },
  { canonicalName: 'Terbinafine 1 %', genericName: 'Terbinafine', brandName: 'Terbinaforce', strength: '1', strengthUnit: '%', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antifungal',
    aliases: ['sebifin', 'sebifin 1', 'terbinafine', 'terbinafine 1', 'terbinaforce', 'terbinaforce 1'] },
  { canonicalName: 'Ketoconazole 2 %', genericName: 'Ketoconazole', brandName: 'Nizral', strength: '2', strengthUnit: '%', dosageForm: 'shampoo', route: 'topical', therapeuticClass: 'Antifungal',
    aliases: ['ketoconazole', 'ketoconazole 2', 'nizral', 'nizral 2'] },
  { canonicalName: 'Clotrimazole (vaginal) 100 mg', genericName: 'Clotrimazole (vaginal)', brandName: 'Candid-V', strength: '100', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antifungal (gynaecological)',
    aliases: ['candid-v', 'candid-v 100', 'clotrimazole (vaginal)', 'clotrimazole (vaginal) 100'] },
  { canonicalName: 'Clotrimazole (vaginal) 500 mg', genericName: 'Clotrimazole (vaginal)', brandName: 'Candid-V', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antifungal (gynaecological)',
    aliases: ['candid-v', 'candid-v 500', 'clotrimazole (vaginal)', 'clotrimazole (vaginal) 500'] },
  { canonicalName: 'Acyclovir 400 mg', genericName: 'Acyclovir', brandName: 'Zovirax', strength: '400', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiviral (herpes)',
    aliases: ['acivir', 'acivir 400', 'acyclovir', 'acyclovir 400', 'zovirax', 'zovirax 400'] },
  { canonicalName: 'Acyclovir 800 mg', genericName: 'Acyclovir', brandName: 'Zovirax', strength: '800', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiviral (herpes)',
    aliases: ['acivir', 'acivir 800', 'acyclovir', 'acyclovir 800', 'zovirax', 'zovirax 800'] },
  { canonicalName: 'Valacyclovir 500 mg', genericName: 'Valacyclovir', brandName: 'Valcivir', strength: '500', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antiviral',
    aliases: ['valacyclovir', 'valacyclovir 500', 'valcivir', 'valcivir 500'] },
  { canonicalName: 'Oseltamivir 75 mg', genericName: 'Oseltamivir', brandName: 'Fluvir', strength: '75', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'Antiviral (influenza)',
    aliases: ['antiflu', 'antiflu 75', 'fluvir', 'fluvir 75', 'oseltamivir', 'oseltamivir 75'] },
  { canonicalName: 'Levothyroxine 25 mcg', genericName: 'Levothyroxine', brandName: 'Eltroxin', strength: '25', strengthUnit: 'mcg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Thyroid hormone replacement',
    aliases: ['eltroxin', 'eltroxin 25', 'levothyroxine', 'levothyroxine 25', 'thyronorm', 'thyronorm 25', 'thyrox', 'thyrox 25'] },
  { canonicalName: 'Levothyroxine 50 mcg', genericName: 'Levothyroxine', brandName: 'Eltroxin', strength: '50', strengthUnit: 'mcg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Thyroid hormone replacement',
    aliases: ['eltroxin', 'eltroxin 50', 'levothyroxine', 'levothyroxine 50', 'thyronorm', 'thyronorm 50', 'thyrox', 'thyrox 50'] },
  { canonicalName: 'Levothyroxine 100 mcg', genericName: 'Levothyroxine', brandName: 'Eltroxin', strength: '100', strengthUnit: 'mcg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Thyroid hormone replacement',
    aliases: ['eltroxin', 'eltroxin 100', 'levothyroxine', 'levothyroxine 100', 'thyronorm', 'thyronorm 100', 'thyrox', 'thyrox 100'] },
  { canonicalName: 'Carbimazole 5 mg', genericName: 'Carbimazole', brandName: 'Neo-Mercazole', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antithyroid',
    aliases: ['carbimazole', 'carbimazole 5', 'neo-mercazole', 'neo-mercazole 5'] },
  { canonicalName: 'Carbimazole 10 mg', genericName: 'Carbimazole', brandName: 'Neo-Mercazole', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antithyroid',
    aliases: ['carbimazole', 'carbimazole 10', 'neo-mercazole', 'neo-mercazole 10'] },
  { canonicalName: 'Paracetamol drops/syrup (infant/child) 100 mg', genericName: 'Paracetamol drops/syrup (infant/child)', brandName: 'Calpol', strength: '100', strengthUnit: 'mg', dosageForm: 'drops', route: 'oral', therapeuticClass: 'Antipyretic',
    aliases: ['calpol', 'calpol 100', 'crocin', 'crocin 100', 'paracetamol drops/syrup (infant/child)', 'paracetamol drops/syrup (infant/child) 100'] },
  { canonicalName: 'Paracetamol drops/syrup (infant/child) 5 ml', genericName: 'Paracetamol drops/syrup (infant/child)', brandName: 'Calpol', strength: '5', strengthUnit: 'ml', dosageForm: 'drops', route: 'oral', therapeuticClass: 'Antipyretic',
    aliases: ['calpol', 'calpol 5', 'crocin', 'crocin 5', 'paracetamol drops/syrup (infant/child)', 'paracetamol drops/syrup (infant/child) 5'] },
  { canonicalName: 'Amoxicillin + Clavulanate syrup 228.5 mg', genericName: 'Amoxicillin + Clavulanate syrup', brandName: 'Augmentin Duo', strength: '228.5', strengthUnit: 'mg', dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Paediatric antibiotic',
    aliases: ['amoxicillin', 'amoxicillin + clavulanate syrup', 'amoxicillin + clavulanate syrup 228.5', 'augmentin duo', 'augmentin duo 228.5', 'clavulanate syrup', 'moxikind-cv', 'moxikind-cv 228.5'] },
  { canonicalName: 'Amoxicillin + Clavulanate syrup 5 ml', genericName: 'Amoxicillin + Clavulanate syrup', brandName: 'Augmentin Duo', strength: '5', strengthUnit: 'ml', dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Paediatric antibiotic',
    aliases: ['amoxicillin', 'amoxicillin + clavulanate syrup', 'amoxicillin + clavulanate syrup 5', 'augmentin duo', 'augmentin duo 5', 'clavulanate syrup', 'moxikind-cv', 'moxikind-cv 5'] },
  { canonicalName: 'Cough & cold syrup (paediatric)', genericName: 'Cough & cold syrup (paediatric)', brandName: 'Benadryl', strength: null, strengthUnit: null, dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Antitussive/expectorant',
    aliases: ['benadryl', 'chericof', 'cough & cold syrup (paediatric)'] },
  { canonicalName: 'Iron tonic syrup', genericName: 'Iron tonic syrup', brandName: 'Dexorange', strength: null, strengthUnit: null, dosageForm: 'syrup', route: 'oral', therapeuticClass: 'Hematinic',
    aliases: ['dexorange', 'iron tonic syrup'] },
  { canonicalName: 'Multivitamin drops/syrup (paediatric)', genericName: 'Multivitamin drops/syrup (paediatric)', brandName: 'Polybion', strength: null, strengthUnit: null, dosageForm: 'drops', route: 'oral', therapeuticClass: 'Multivitamin',
    aliases: ['multivitamin drops/syrup (paediatric)', 'polybion', 'zincovit'] },
  { canonicalName: 'Cetirizine drops (paediatric) 2.5 mg', genericName: 'Cetirizine drops (paediatric)', brandName: 'Cetzine', strength: '2.5', strengthUnit: 'mg', dosageForm: 'drops', route: 'oral', therapeuticClass: 'Antihistamine',
    aliases: ['alerid', 'alerid 2.5', 'cetirizine drops (paediatric)', 'cetirizine drops (paediatric) 2.5', 'cetzine', 'cetzine 2.5'] },
  { canonicalName: 'Albendazole suspension (paediatric) 200 mg', genericName: 'Albendazole suspension (paediatric)', brandName: 'Zentel', strength: '200', strengthUnit: 'mg', dosageForm: 'suspension', route: 'oral', therapeuticClass: 'Anthelmintic',
    aliases: ['albendazole suspension (paediatric)', 'albendazole suspension (paediatric) 200', 'wormin', 'wormin 200', 'zentel', 'zentel 200'] },
  { canonicalName: 'Albendazole suspension (paediatric) 5 ml', genericName: 'Albendazole suspension (paediatric)', brandName: 'Zentel', strength: '5', strengthUnit: 'ml', dosageForm: 'suspension', route: 'oral', therapeuticClass: 'Anthelmintic',
    aliases: ['albendazole suspension (paediatric)', 'albendazole suspension (paediatric) 5', 'wormin', 'wormin 5', 'zentel', 'zentel 5'] },
  { canonicalName: 'Domperidone suspension (paediatric) 5 mg', genericName: 'Domperidone suspension (paediatric)', brandName: 'Domstal', strength: '5', strengthUnit: 'mg', dosageForm: 'suspension', route: 'oral', therapeuticClass: 'Antiemetic/prokinetic',
    aliases: ['domperidone suspension (paediatric)', 'domperidone suspension (paediatric) 5', 'domstal', 'domstal 5', 'vomistop', 'vomistop 5'] },
  { canonicalName: 'Domperidone suspension (paediatric) 5 ml', genericName: 'Domperidone suspension (paediatric)', brandName: 'Domstal', strength: '5', strengthUnit: 'ml', dosageForm: 'suspension', route: 'oral', therapeuticClass: 'Antiemetic/prokinetic',
    aliases: ['domperidone suspension (paediatric)', 'domperidone suspension (paediatric) 5', 'domstal', 'domstal 5', 'vomistop', 'vomistop 5'] },
  { canonicalName: 'Diazepam 5 mg', genericName: 'Diazepam', brandName: 'Calmpose', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Benzodiazepine (anxiolytic/sedative)',
    aliases: ['calmpose', 'calmpose 5', 'diazepam', 'diazepam 5'] },
  { canonicalName: 'Alprazolam 0.25 mg', genericName: 'Alprazolam', brandName: 'Alprax', strength: '0.25', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Benzodiazepine (anxiolytic)',
    aliases: ['alprax', 'alprax 0.25', 'alprazolam', 'alprazolam 0.25', 'restyl', 'restyl 0.25'] },
  { canonicalName: 'Alprazolam 0.5 mg', genericName: 'Alprazolam', brandName: 'Alprax', strength: '0.5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Benzodiazepine (anxiolytic)',
    aliases: ['alprax', 'alprax 0.5', 'alprazolam', 'alprazolam 0.5', 'restyl', 'restyl 0.5'] },
  { canonicalName: 'Escitalopram 10 mg', genericName: 'Escitalopram', brandName: 'Nexito', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'SSRI antidepressant',
    aliases: ['escitalopram', 'escitalopram 10', 'nexito', 'nexito 10'] },
  { canonicalName: 'Sertraline 50 mg', genericName: 'Sertraline', brandName: 'Serlift', strength: '50', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'SSRI antidepressant',
    aliases: ['serlift', 'serlift 50', 'sertraline', 'sertraline 50'] },
  { canonicalName: 'Amitriptyline 10 mg', genericName: 'Amitriptyline', brandName: 'Tryptomer', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Tricyclic antidepressant (neuropathic pain/migraine ppx)',
    aliases: ['amitriptyline', 'amitriptyline 10', 'tryptomer', 'tryptomer 10'] },
  { canonicalName: 'Amitriptyline 25 mg', genericName: 'Amitriptyline', brandName: 'Tryptomer', strength: '25', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Tricyclic antidepressant (neuropathic pain/migraine ppx)',
    aliases: ['amitriptyline', 'amitriptyline 25', 'tryptomer', 'tryptomer 25'] },
  { canonicalName: 'Propranolol 10 mg', genericName: 'Propranolol', brandName: 'Ciplar', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta blocker (migraine ppx/tremor/anxiety)',
    aliases: ['ciplar', 'ciplar 10', 'propranolol', 'propranolol 10'] },
  { canonicalName: 'Propranolol 40 mg', genericName: 'Propranolol', brandName: 'Ciplar', strength: '40', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta blocker (migraine ppx/tremor/anxiety)',
    aliases: ['ciplar', 'ciplar 40', 'propranolol', 'propranolol 40'] },
  { canonicalName: 'Flunarizine 5 mg', genericName: 'Flunarizine', brandName: 'Sibelium', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Migraine prophylaxis',
    aliases: ['flunarizine', 'flunarizine 5', 'sibelium', 'sibelium 5'] },
  { canonicalName: 'Flunarizine 10 mg', genericName: 'Flunarizine', brandName: 'Sibelium', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Migraine prophylaxis',
    aliases: ['flunarizine', 'flunarizine 10', 'sibelium', 'sibelium 10'] },
  { canonicalName: 'Duloxetine 20 mg', genericName: 'Duloxetine', brandName: 'Duzela', strength: '20', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'SNRI (neuropathic pain/depression)',
    aliases: ['duloxetine', 'duloxetine 20', 'duzela', 'duzela 20'] },
  { canonicalName: 'Duloxetine 30 mg', genericName: 'Duloxetine', brandName: 'Duzela', strength: '30', strengthUnit: 'mg', dosageForm: 'capsule', route: 'oral', therapeuticClass: 'SNRI (neuropathic pain/depression)',
    aliases: ['duloxetine', 'duloxetine 30', 'duzela', 'duzela 30'] },
  { canonicalName: 'Methylprednisolone 4 mg', genericName: 'Methylprednisolone', brandName: 'Medrol', strength: '4', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Corticosteroid',
    aliases: ['medrol', 'medrol 4', 'methylprednisolone', 'methylprednisolone 4'] },
  { canonicalName: 'Methylprednisolone 8 mg', genericName: 'Methylprednisolone', brandName: 'Medrol', strength: '8', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Corticosteroid',
    aliases: ['medrol', 'medrol 8', 'methylprednisolone', 'methylprednisolone 8'] },
  { canonicalName: 'Methylprednisolone 16 mg', genericName: 'Methylprednisolone', brandName: 'Medrol', strength: '16', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Corticosteroid',
    aliases: ['medrol', 'medrol 16', 'methylprednisolone', 'methylprednisolone 16'] },
  { canonicalName: 'Prednisolone 5 mg', genericName: 'Prednisolone', brandName: 'Wysolone', strength: '5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Corticosteroid',
    aliases: ['prednisolone', 'prednisolone 5', 'wysolone', 'wysolone 5'] },
  { canonicalName: 'Prednisolone 10 mg', genericName: 'Prednisolone', brandName: 'Wysolone', strength: '10', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Corticosteroid',
    aliases: ['prednisolone', 'prednisolone 10', 'wysolone', 'wysolone 10'] },
  { canonicalName: 'Prednisolone 20 mg', genericName: 'Prednisolone', brandName: 'Wysolone', strength: '20', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Corticosteroid',
    aliases: ['prednisolone', 'prednisolone 20', 'wysolone', 'wysolone 20'] },
  { canonicalName: 'Dexamethasone 0.5 mg', genericName: 'Dexamethasone', brandName: 'Decadron', strength: '0.5', strengthUnit: 'mg', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Corticosteroid',
    aliases: ['decadron', 'decadron 0.5', 'dexamethasone', 'dexamethasone 0.5'] },
  { canonicalName: 'Polyherbal hepatoprotective (not a single molecule)', genericName: 'Polyherbal hepatoprotective (not a single molecule)', brandName: 'Liv.52', strength: null, strengthUnit: null, dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Hepatoprotective (Ayurvedic proprietary formulation)',
    aliases: ['liv.52', 'polyherbal hepatoprotective (not a single molecule)'] },
  { canonicalName: 'Chloramphenicol (eye) 1 %', genericName: 'Chloramphenicol (eye)', brandName: 'Chloromycetin', strength: '1', strengthUnit: '%', dosageForm: 'drops', route: 'oral', therapeuticClass: 'Ophthalmic antibiotic',
    aliases: ['chloramphenicol (eye)', 'chloramphenicol (eye) 1', 'chloromycetin', 'chloromycetin 1'] },
  { canonicalName: 'Ciprofloxacin (eye/ear) 0.3 %', genericName: 'Ciprofloxacin (eye/ear)', brandName: 'Ciplox', strength: '0.3', strengthUnit: '%', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Ophthalmic/otic antibiotic',
    aliases: ['ciplox', 'ciplox 0.3', 'ciprofloxacin (eye/ear)', 'ciprofloxacin (eye/ear) 0.3'] },
  { canonicalName: 'Gentamicin (eye) 0.3 %', genericName: 'Gentamicin (eye)', brandName: 'Genticyn', strength: '0.3', strengthUnit: '%', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Ophthalmic antibiotic (aminoglycoside)',
    aliases: ['gentamicin (eye)', 'gentamicin (eye) 0.3', 'genticyn', 'genticyn 0.3'] },
  { canonicalName: 'Timolol (eye) 0.5 %', genericName: 'Timolol (eye)', brandName: 'Timoptol', strength: '0.5', strengthUnit: '%', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Beta blocker (glaucoma)',
    aliases: ['timolol (eye)', 'timolol (eye) 0.5', 'timoptol', 'timoptol 0.5'] },
  { canonicalName: 'Olopatadine (eye) 0.1 %', genericName: 'Olopatadine (eye)', brandName: 'Patanol', strength: '0.1', strengthUnit: '%', dosageForm: 'tablet', route: 'oral', therapeuticClass: 'Antihistamine (allergic conjunctivitis)',
    aliases: ['olopatadine (eye)', 'olopatadine (eye) 0.1', 'patanol', 'patanol 0.1'] },
];
