/**
 * India's legally restricted medicines — primary-sourced.
 *
 * GENERATED from research against CDSCO's consolidated Drugs Rules, the Central
 * Bureau of Narcotics quantity notification, and court judgments quoting gazette
 * numbers. 82 molecules, of which 42 block telemedicine prescribing.
 *
 * THREE CORRECTIONS THIS DATA FORCED ON THE HAND-WRITTEN VERSION
 *
 * 1. Schedule X has SIXTEEN entries, not the "~40" that circulates online. That
 *    figure is a stale pre-1998 version of the schedule; deletions moved most
 *    items out. Most of the sixteen are obsolete or illicit with no Indian brand.
 *
 * 2. Schedule X and Schedule H1 are SEPARATE AND NON-OVERLAPPING. The drugs
 *    everyone assumes are Schedule X — tramadol, diazepam, alprazolam,
 *    buprenorphine, codeine — are legally Schedule H1. They still block, but
 *    because they are NDPS-scheduled, not because they are Schedule X. Getting
 *    this wrong would have mislabelled exactly the drugs that matter most.
 *
 * 3. §3.7.4's prohibited list is Schedule X + NDPS ONLY. Schedule H1-only drugs
 *    (most antibiotics, anti-TB drugs, oxytocin) are NOT on it — they need the
 *    pharmacist's H1 register when dispensed, which is not a prescribing ban.
 *    They are carried here with blockTelemedicine: false so the distinction is
 *    explicit rather than implied by absence.
 *
 * Dextropropoxyphene is banned outright in India (s.26A, since 2013), not merely
 * restricted. Zopiclone and modafinil could not be confirmed either way from any
 * primary source; they block anyway, because failing closed on an unconfirmed
 * psychotropic is the cheap mistake and failing open is the expensive one.
 */

export interface RestrictedEntry {
  molecule: string;
  /** 'X' Schedule X · 'NDPS' narcotic/psychotropic · 'H1' register only. */
  schedule: 'X' | 'NDPS' | 'H1';
  /** Whether §3.7.4 prohibits prescribing this remotely. */
  blockTelemedicine: boolean;
  /** How well the SCHEDULE placement is sourced, not the brand list. */
  confidence: string;
  /** Substrings that identify it, matched at a word boundary. */
  stems: string[];
  /** Indian brand names. Doctors dictate these, not molecules. */
  brands: string[];
}

export const RESTRICTED_INDIA: RestrictedEntry[] = [
  { molecule: 'Amobarbital', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['amobarbital'],
    brands: [] },
  { molecule: 'Phencyclidine', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['phencyclidine'],
    brands: [] },
  { molecule: 'Dexamphetamine', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['dexamphetamine'],
    brands: [] },
  { molecule: 'Glutethimide', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['glutethimide'],
    brands: [] },
  { molecule: 'Barbital', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['barbital'],
    brands: [] },
  { molecule: 'Methylphenidate', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['addwize', 'atendate sr-54', 'inspiral', 'mdet', 'mdet sr', 'methylphenidate', 'ritalin'],
    brands: ['Mdet', 'Mdet SR', 'Atendate SR-54'] },
  { molecule: 'Pentobarbital', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['pentobarbital'],
    brands: [] },
  { molecule: 'Methamphetamine', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['methamphetamine'],
    brands: [] },
  { molecule: 'Secobarbital', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['secobarbital'],
    brands: [] },
  { molecule: 'Ketamine hydrochloride', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['aneket', 'ketamine', 'ketamine hydrochloride', 'ketmin'],
    brands: [] },
  { molecule: 'Phenmetrazine', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['phenmetrazine'],
    brands: [] },
  { molecule: 'Ethclorvynol', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['ethclorvynol'],
    brands: [] },
  { molecule: 'Amphetamine', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['amphetamine'],
    brands: [] },
  { molecule: 'Cyclobarbital', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['cyclobarbital'],
    brands: [] },
  { molecule: 'Methylphenobarbital', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['gardenal', 'luminal', 'methylphenobarbital'],
    brands: [] },
  { molecule: 'Meprobamate', schedule: 'X', blockTelemedicine: true, confidence: 'high',
    stems: ['equanil', 'meprobamate'],
    brands: ['Equanil'] },
  { molecule: 'Morphine', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['morcontin', 'morphine', 'morphitroy', 'mscontin', 'rilitin', 'rumorf'],
    brands: ['Rumorf', 'Morphitroy'] },
  { molecule: 'Fentanyl', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['durogesic', 'fenspar', 'fentanyl', 'fentapatch', 'rufenyl', 'trofentyl'],
    brands: ['Fenspar', 'Rufenyl'] },
  { molecule: 'Codeine', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['codeine', 'codistar', 'corex', 'grilinctus cd', 'phensedyl'],
    brands: ['Phensedyl'] },
  { molecule: 'Pethidine (meperidine)', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['pethidine', 'pethidine (meperidine)'],
    brands: [] },
  { molecule: 'Methadone', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['methadone'],
    brands: [] },
  { molecule: 'Oxycodone', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['oxycodone'],
    brands: [] },
  { molecule: 'Dextropropoxyphene', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['dextropropoxyphene'],
    brands: [] },
  { molecule: 'Buprenorphine', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['addnok', 'azitrix', 'bue-spar', 'bue-touch', 'bupatch', 'bupoxone', 'buprenorphine', 'bupreplast', 'buprigesic', 'buptrans', 'buvalor', 'norphin', 'rupatch', 'sangesic', 'sispatch', 'tidigesic', 'zuprinor'],
    brands: ['Buvalor', 'Addnok', 'Buprigesic', 'Zuprinor', 'Sangesic', 'Bupatch', 'Bue-Touch', 'Rupatch', 'Bupreplast', 'Buptrans', 'Bupoxone', 'Sispatch', 'Bue-Spar', 'Azitrix', 'Tidigesic'] },
  { molecule: 'Pentazocine', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['fortwin', 'ipzocin', 'pentawin', 'pentazocine', 'ruwin', 'tazowin', 'zocifix'],
    brands: ['Ipzocin', 'Zocifix', 'Tazowin', 'Ruwin', 'Fortwin'] },
  { molecule: 'Tramadol', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['contramal', 'dolmundin', 'domadol', 'kamadol', 'neutram', 'supridol', 'tradol', 'tramacip', 'tramadex', 'tramadol', 'tramadus', 'tramatas', 'tramazac', 'trd contin od', 'ultracet'],
    brands: ['Domadol', 'Tramadex', 'Tramatas', 'Dolmundin', 'Kamadol', 'Supridol', 'Contramal', 'Tramazac', 'TRD Contin OD', 'Neutram', 'Tradol', 'Tramadus', 'Ultracet'] },
  { molecule: 'Alprazolam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['alora', 'alprax', 'alprazolam', 'alprocontin', 'alzolam', 'anxit', 'restyl', 'texidep', 'trika', 'zolam', 'zolax', 'zolipax'],
    brands: ['Alprax', 'Trika', 'Anxit', 'Alzolam', 'Restyl', 'Zolam', 'Texidep', 'Alprocontin', 'Alora', 'Zolipax'] },
  { molecule: 'Diazepam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['calmpose', 'calmzep', 'diacalm', 'diazepam', 'dizy', 'lori', 'peacin', 'peptica', 'placidox', 'repam', 'shipam', 'valium'],
    brands: ['Calmpose', 'Shipam', 'Diacalm', 'Peacin', 'Peptica', 'Repam', 'Calmzep', 'Valium', 'Lori'] },
  { molecule: 'Clonazepam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['aplaz', 'aplaz md', 'aplaz-d', 'clonazepam', 'clonotril', 'czam', 'ecotril', 'epitril', 'linotril', 'lonafest', 'lonator md', 'lonazep', 'lonna', 'melzap md', 'ona md', 'ozepam', 'petril', 'petril-md', 'rivotril', 'zapiz'],
    brands: ['Aplaz', 'Aplaz-D', 'Aplaz MD', 'Czam', 'Ecotril', 'Epitril', 'Melzap MD', 'Linotril', 'Ozepam', 'Ona', 'Ona MD', 'Lonna', 'Lonator MD', 'Lonafest', 'Petril', 'Petril-MD'] },
  { molecule: 'Lorazepam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['ativan', 'laprose', 'larpose', 'locest', 'logan', 'lopez', 'loranxit', 'lorapax', 'lorawel', 'loraz', 'lorazepam', 'loricalm', 'loripam', 'lotranz', 'loxum', 'lozem', 'orazep', 'proline', 'trapex', 'zepnap'],
    brands: ['Orazep', 'Lorawel', 'Loripam', 'Loranxit', 'Laprose', 'Lozem', 'Logan', 'Locest', 'Lotranz', 'Loxum', 'Loraz', 'Proline', 'Loricalm', 'Zepnap', 'Lorapax'] },
  { molecule: 'Nitrazepam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['calmtra', 'hypnosed', 'nipam', 'nipamp', 'nira', 'nitab', 'nitaz', 'nitcalm', 'nithra', 'nitizam', 'nitpam', 'nitpro', 'nitravet', 'nitrazepam', 'nitrofen', 'nitrosun', 'sedamon', 'sonip', 'sopor', 'tritnit', 'v nit'],
    brands: ['Hypnosed', 'Calmtra', 'Sonip', 'Nitrofen', 'Nipamp', 'Nitravet', 'Nitcalm', 'Nitpro', 'Nithra', 'Nitaz', 'Nipam', 'Sopor', 'V Nit', 'Nitizam', 'Tritnit', 'Nitpam', 'Nitab', 'NAP', 'Nira'] },
  { molecule: 'Chlordiazepoxide', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['anxibrium', 'anxide', 'anxon', 'cd-pox', 'chlordiazepoxide', 'equilibrium', 'equirex', 'hioch md', 'hioch plus', 'librate', 'librium', 'lorxide', 'xide', 'zepoxife'],
    brands: ['Anxon', 'Equilibrium', 'Librium', 'Librate', 'Xide', 'Zepoxife', 'CD-Pox', 'Hioch Plus', 'Anxibrium', 'Lorxide', 'Anxide', 'Hioch MD'] },
  { molecule: 'Midazolam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['benzosed', 'da plus', 'fulsed', 'insed', 'kabizolam', 'lamzomid ns', 'medistat', 'medrasol', 'medzol', 'mezolam', 'midacare', 'midacip', 'midasiz', 'midazolam', 'midazom', 'midfast', 'midfix'],
    brands: ['Mezolam', 'Midfast', 'Midacip', 'Benzosed', 'Midasiz', 'Midfix', 'Midazom', 'Insed', 'Medistat', 'Kabizolam', 'Medzol', 'Medrasol', 'Lamzomid NS', 'Da Plus', 'Midacare'] },
  { molecule: 'Flunitrazepam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['flunitrazepam', 'nitravet', 'nitrosun', 'sedamon'],
    brands: [] },
  { molecule: 'Triazolam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['triazolam'],
    brands: [] },
  { molecule: 'Zolpidem', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['adsleep', 'freza', 'nitrest', 'sove', 'sove it', 'stilnoct', 'zmolly', 'zoldy', 'zolfit', 'zolfree', 'zolfresh', 'zolfresh odt', 'zolgo', 'zolmoon', 'zolnap', 'zolnap-xr', 'zolpeace', 'zolpidem', 'zolpirest', 'zolsam', 'zolway'],
    brands: ['Adsleep', 'Sove IT', 'Sove', 'Stilnoct', 'Zolpirest', 'Zolway', 'Zolpeace', 'Zolnap', 'Zolnap-XR', 'Zolgo', 'Zoldy', 'Zolfree', 'Zolfit', 'Zolmoon', 'Freza', 'Zmolly', 'Zolfresh ODT', 'Zolsam'] },
  { molecule: 'Etizolam', schedule: 'NDPS', blockTelemedicine: true, confidence: 'medium-high',
    stems: ['etidip', 'etilaam', 'etilof cr', 'etimax', 'etimind md', 'etimood', 'etinap', 'etisum', 'etisyn', 'etizep', 'etizest', 'etizola', 'etizolam', 'etnizex', 'macfresh', 'mezilor', 'neprazolam', 'suprabenz'],
    brands: ['Mezilor', 'Suprabenz', 'Etizola', 'Etilaam', 'Etisyn', 'Etinap', 'Etizep', 'Macfresh', 'Etilof CR', 'Elm', 'Etimind MD', 'Neprazolam', 'Etimood', 'Etizest', 'Etimax', 'Etnizex', 'Ezo', 'Etidip'] },
  { molecule: 'Phenobarbital (phenobarbitone)', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['barbex', 'gardenal', 'luminal', 'phenobarb', 'phenobarbital', 'phenobarbital (phenobarbitone)'],
    brands: ['Gardenal', 'Phenobarb', 'Barbex'] },
  { molecule: 'Butalbital', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['butalbital'],
    brands: [] },
  { molecule: 'Methaqualone', schedule: 'NDPS', blockTelemedicine: true, confidence: 'high',
    stems: ['methaqualone'],
    brands: [] },
  { molecule: 'Zopiclone', schedule: 'NDPS', blockTelemedicine: true, confidence: 'low',
    stems: ['nunorm', 'zolium', 'zopiclone', 'zopicon'],
    brands: ['Zopicon'] },
  { molecule: 'Modafinil', schedule: 'NDPS', blockTelemedicine: true, confidence: 'low',
    stems: ['modafinil'],
    brands: [] },
  { molecule: 'Balofloxacin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['balofloxacin'],
    brands: [] },
  { molecule: 'Capreomycin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['capreomycin'],
    brands: [] },
  { molecule: 'Cefdinir', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['cefdinir'],
    brands: [] },
  { molecule: 'Cefditoren', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['cefditoren'],
    brands: [] },
  { molecule: 'Cefepime', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['cefepime'],
    brands: [] },
  { molecule: 'Cefetamet', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['cefetamet'],
    brands: [] },
  { molecule: 'Cefixime', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['brutacef', 'cefi dt', 'cefilab', 'cefimo', 'cefivot', 'cefix', 'cefixain', 'cefixime', 'cefiza', 'cefnij', 'cefrax', 'ctax o', 'decef', 'delbi', 'eficin', 'epime'],
    brands: ['Cefixain', 'Cefrax', 'Cefix', 'Ctax O', 'Decef', 'Delbi', 'Eficin', 'Epime', 'Brutacef', 'Cefi DT', 'Cefilab', 'Cefnij', 'Cefimo', 'Cefiza', 'Cefivot'] },
  { molecule: 'Cefoperazone', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['cefoperazone'],
    brands: [] },
  { molecule: 'Cefotaxime', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['biotax', 'cefantral', 'cefotaxime', 'ctax', 'omnicef', 'oritaxim'],
    brands: ['Oritaxim', 'Ctax', 'Cefantral', 'Omnicef', 'Biotax'] },
  { molecule: 'Cefpirome', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['cefpirome'],
    brands: [] },
  { molecule: 'Cefpodoxime', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['bactogard dt', 'cedon dt', 'cefpod dt', 'cefpodoxime', 'cumin', 'cupal', 'grandcef', 'kefmax', 'kefodime', 'kefpod dt', 'microcef', 'oxipod dt', 'pecef', 'polypod', 'poxim', 'safpod', 'spectratil', 'spectratil ds', 'suprapod', 'swich', 'tambac', 'zuef o'],
    brands: ['Oxipod DT', 'Kefpod DT', 'Kefmax', 'Kefodime', 'Spectratil', 'Spectratil DS', 'Microcef', 'Polypod', 'Poxim', 'Pecef', 'Cumin', 'Cupal', 'Suprapod', 'Swich', 'Tambac', 'Safpod', 'Zuef O', 'Cefpod DT', 'Grandcef', 'Bactogard DT', 'Cedon DT'] },
  { molecule: 'Ceftazidime', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['c zid', 'cefactiv', 'ceftaz', 'ceftazidime', 'cefwide', 'fortacef', 'forzid', 'keftaglan', 'stef', 'tazid'],
    brands: ['Ceftaz', 'Stef', 'Tazid', 'Forzid', 'C Zid', 'Cefactiv', 'Cefwide', 'Fortacef', 'Keftaglan'] },
  { molecule: 'Ceftibuten', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['ceftibuten'],
    brands: [] },
  { molecule: 'Ceftizoxime', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['ceftizoxime'],
    brands: [] },
  { molecule: 'Ceftriaxone', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['c-tri', 'cefaxone', 'ceftriaxone', 'ceftron', 'hetexone', 'maczone', 'monocef', 'odicef', 'oframax', 'taxone', 'traxol', 'xone'],
    brands: ['Monocef', 'Xone', 'Odicef', 'Traxol', 'Oframax', 'Hetexone', 'Maczone', 'Cefaxone', 'C-Tri', 'Taxone', 'Ceftron'] },
  { molecule: 'Clofazimine', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['clofazimine', 'hansepran'],
    brands: ['Hansepran'] },
  { molecule: 'Cycloserine', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['cycloserine'],
    brands: [] },
  { molecule: 'Diphenoxylate', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['diphenoxylate'],
    brands: [] },
  { molecule: 'Doripenem', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['doripenem'],
    brands: [] },
  { molecule: 'Ertapenem', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['ertapenem'],
    brands: [] },
  { molecule: 'Ethambutol Hydrochloride', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['combutol', 'ecox', 'ethambutol', 'ethambutol hydrochloride', 'mycobutol', 'sunibutol'],
    brands: ['Mycobutol', 'Sunibutol', 'Ecox', 'Combutol'] },
  { molecule: 'Ethionamide', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['ethionamide'],
    brands: [] },
  { molecule: 'Faropenem', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['faropenem'],
    brands: [] },
  { molecule: 'Gemifloxacin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['g-cin', 'gemifloxacin'],
    brands: ['G-Cin'] },
  { molecule: 'Imipenem', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['imipenem'],
    brands: [] },
  { molecule: 'Isoniazid', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['isoniazid', 'pyzina kid', 'solonex', 'solonex dt'],
    brands: ['Solonex', 'Solonex DT', 'Pyzina Kid'] },
  { molecule: 'Levofloxacin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['alevo', 'fynal', 'l-cin', 'levocin', 'levofloxacin', 'levomac', 'levorich', 'levotas', 'lotor', 'lovolkem', 'lquin', 'mahalevo', 'qulef', 'ultramycin', 'veloxin'],
    brands: ['Lovolkem', 'LQUIN', 'Levotas', 'Mahalevo', 'LOTOR', 'Alevo', 'ULTRAMYCIN', 'VELOXIN', 'L-Cin', 'Lee', 'Levomac', 'Levocin', 'Levorich', 'Fynal', 'Qulef'] },
  { molecule: 'Meropenem', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['aktimer', 'inzapenum', 'ivpenem', 'merofit', 'meronir', 'meropenem', 'meropenia', 'merowin', 'mexopen', 'neopenem', 'penmer', 'unomero', 'winmero'],
    brands: ['Unomero', 'Inzapenum', 'Penmer', 'Meronir', 'Merowin', 'Aktimer', 'Neopenem', 'Mexopen', 'Meropenia', 'Ivpenem', 'Merofit', 'Winmero'] },
  { molecule: 'Moxifloxacin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['emfozen', 'floxsafe', 'kitmox', 'mflotas', 'mighty mox', 'mofex', 'moforx', 'moxifax', 'moxifloxacin', 'moxifur', 'moxigram', 'moxisure', 'moxitak', 'moxivail', 'moxplore', 'moxrun', 'moxtif', 'onemox', 'vigoquin', 'zoptina'],
    brands: ['Emfozen', 'Moxifax', 'Moxifur', 'MOXITAK', 'MOXIGRAM', 'Moxtif', 'Moxisure', 'Floxsafe', 'Mflotas', 'Kitmox', 'Moxplore', 'Onemox', 'Mofex', 'Vigoquin', 'Zoptina', 'Moforx', 'Moxrun', 'Mighty Mox', 'Moxivail'] },
  { molecule: 'Prulifloxacin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['prulifloxacin'],
    brands: [] },
  { molecule: 'Pyrazinamide', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['macrozide', 'p-zide', 'pyrazinamide', 'pyzina', 'pza ciba'],
    brands: ['PZA CIBA', 'Macrozide', 'P-Zide', 'Pyzina'] },
  { molecule: 'Rifabutin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['ributin', 'rifabutin'],
    brands: ['Ributin'] },
  { molecule: 'Rifampicin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['geno-mix', 'macox', 'r-cin', 'rifampicin'],
    brands: ['Macox', 'Geno-Mix', 'R-Cin'] },
  { molecule: 'Sodium Para-aminosalicylate', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['sodium', 'sodium para-aminosalicylate'],
    brands: [] },
  { molecule: 'Sparfloxacin', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['sparfloxacin'],
    brands: [] },
  { molecule: 'Thiacetazone', schedule: 'H1', blockTelemedicine: false, confidence: 'medium-high',
    stems: ['thiacetazone'],
    brands: [] },
  { molecule: 'Oxytocin', schedule: 'H1', blockTelemedicine: false, confidence: 'high',
    stems: ['evatocin', 'gynotocin', 'kaptocin', 'oxytocin', 'pitocin', 'syntocinon'],
    brands: ['Syntocinon', 'GYNOTOCIN', 'Kaptocin', 'Pitocin', 'Evatocin'] },
  { molecule: 'Tapentadol', schedule: 'H1', blockTelemedicine: false, confidence: 'high',
    stems: ['nudol', 'oncodol', 'tapal', 'tapcare er', 'tapdol', 'tapenax er', 'tapentadol', 'tepedict', 'topentex', 'ultraniche-t'],
    brands: ['Nudol', 'Tepedict', 'Ultraniche-T', 'Tapal', 'Tapenax ER', 'Topentex', 'Oncodol', 'Tapdol', 'Tapcare ER'] },
  { molecule: 'Oseltamivir', schedule: 'H1', blockTelemedicine: false, confidence: 'low (H1 membership unconfirmed; the drug itself definitely exists and is widely marketed)',
    stems: ['amiflu', 'antiflu', 'arv-flu', 'flucover', 'fluvir', 'olpavir', 'oltavir', 'omavir', 'oselneed', 'oseltamivir', 'oseltapen', 'osmeflu', 'tamibid', 'tamibliss', 'tamigain'],
    brands: ['Flucover', 'Oltavir', 'Fluvir', 'Tamibliss', 'Tamigain', 'Tamibid', 'Olpavir', 'Osmeflu', 'Amiflu', 'Oseltapen', 'ARV-Flu', 'Oselneed', 'Omavir', 'Antiflu'] },
  { molecule: 'Zanamivir', schedule: 'H1', blockTelemedicine: false, confidence: 'low (H1 membership unconfirmed)',
    stems: ['zanamivir'],
    brands: [] },
];
