name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: npm install
      working-directory: ./health-hub-backend
    - run: npm run lint
      working-directory: ./health-hub-backend
      continue-on-error: true
    - run: npm run type-check
      working-directory: ./health-hub-backend
